### ISSUE TITLE
Student accuracy way below expected

### ISSUE THREAD

**Issue by alexzhang0825** [lenscloth/RKD#18]
Hello,

When I trained with the CUB200 dataset with the embedding size of 64 using resnet18, the student's accuracy is only at about 54 while I saw that on the paper it should be around 58. The teacher is trained under the same dataset with a embedding size of 512 and resnet 50, and its accuracy is still lower but not nearly as much at 59 against 61 from the paper. I was wondering if you knew anything that could cause this. No change was made to the code when I ran it.

**Comment by lenscloth** [comment]
@alexzhang0825 
Can you specify the detailed commands that you used for the experiments?

**Comment by alexzhang0825** [comment]
Hi. I believe it is
```python run_distill.py --dataset cub200 --base googlenet --embedding_size 64 --teacher_base resnet50 --teacher_embedding_size 512 --teacher_load teacher/best.pth --dist_ratio 1  --angle_ratio 2 --save_dir student```

**Comment by lenscloth** [comment]
@alexzhang0825 In the paper, we utilized resent18 as the backbone network for students in the Table 1.
```python run_distill.py --dataset cub200 --base googlenet --embedding_size 64 --teacher_base resnet50 --teacher_embedding_size 512 --teacher_load teacher/best.pth --dist_ratio 1 --angle_ratio 2 --save_dir student```

However, the command above using googlenet as the base student model.
Moreover, during distiilation not applying l2 normalziation was way better in our experiments.

It seems that  I made wrong quick start script.
I will modify the README, can you please run this script instead??

```python run_distill.py --dataset cub200 --base resnet18 --l2normalize false --embedding_size 64 --teacher_base resnet50 --teacher_embedding_size 512 --teacher_load teacher/best.pth --dist_ratio 1 --angle_ratio 2 --save_dir student```

**Comment by alexzhang0825** [comment]
I see. I will run the provided script and see if that will improve things. Thanks a lot.

**Comment by alexzhang0825** [comment]
Hello, I just ran into an error and I figured maybe it should be posted here instead of a new issue as it's related. When I proceeded to the next step where I evaluated using
```!python run.py --mode eval --dataset cub200 --base googlenet --embedding_size 64 --load student/best.pth```
I was given the following error:
```
Using downloaded and verified file: data/googlenet.h5
/content/gdrive/My Drive/project_folder/RKD/model/backbone/inception/google.py:66: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  self.load_state_dict({k: torch.from_numpy(v[group_key].value) for k, v in h5_file[group_key].items()})
Using downloaded and verified file: data/CUB_200_2011.tgz
Using downloaded and verified file: data/CUB_200_2011.tgz
Using downloaded and verified file: data/CUB_200_2011.tgz
Number of images in Training Set: 5864
Number of images in Test set: 5924
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "run.py", line 137, in <module>
    model.load_state_dict(torch.load(opts.load))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LinearEmbedding:
	Missing key(s) in state_dict: "base.conv1.7x7_s2.weight", "base.conv1.7x7_s2.bias", "base.conv2.3x3_reduce.weight", "base.conv2.3x3_reduce.bias", "base.conv2.3x3.weight", "base.conv2.3x3.bias", "base.inception_3a.1x1.weight", "base.inception_3a.1x1.bias", "base.inception_3a.3x3_reduce.weight", "base.inception_3a.3x3_reduce.bias", "base.inception_3a.3x3.weight", "base.inception_3a.3x3.bias", "base.inception_3a.5x5_reduce.weight", "base.inception_3a.5x5_reduce.bias", "base.inception_3a.5x5.weight", "base.inception_3a.5x5.bias", "base.inception_3a.pool_proj.weight", "base.inception_3a.pool_proj.bias", "base.inception_3b.1x1.weight", "base.inception_3b.1x1.bias", "base.inception_3b.3x3_reduce.weight", "base.inception_3b.3x3_reduce.bias", "base.inception_3b.3x3.weight", "base.inception_3b.3x3.bias", "base.inception_3b.5x5_reduce.weight", "base.inception_3b.5x5_reduce.bias", "base.inception_3b.5x5.weight", "base.inception_3b.5x5.bias", "base.inception_3b.pool_proj.weight", "base.inception_3b.pool_proj.bias", "base.inception_4a.1x1.weight", "base.inception_4a.1x1.bias", "base.inception_4a.3x3_reduce.weight", "base.inception_4a.3x3_reduce.bias", "base.inception_4a.3x3.weight", "base.inception_4a.3x3.bias", "base.inception_4a.5x5_reduce.weight", "base.inception_4a.5x5_reduce.bias", "base.inception_4a.5x5.weight", "base.inception_4a.5x5.bias", "base.inception_4a.pool_proj.weight", "base.inception_4a.pool_proj.bias", "base.inception_4b.1x1.weight", "base.inception_4b.1x1.bias", "base.inception_4b.3x3_reduce.weight", "base.inception_4b.3x3_reduce.bias", "base.inception_4b.3x3.weight", "base.inception_4b.3x3.bias", "base.inception_4b.5x5_reduce.weight", "base.inception_4b.5x5_reduce.bias", "base.inception_4b.5x5.weight", "base.inception_4b.5x5.bias", "base.inception_4b.pool_proj.weight", "base.inception_4b.pool_proj.bias", "base.inception_4c.1x1.weight", "base.inception_4c.1x1.bias", "base.inception_4c.3x3_reduce.weight", "base.inception_4c.3x3_reduce.bias", "base.inception_4c.3x3.weight", "base.inception_4c.3x3.bias", "base.inception_4c.5x5_reduce.weight", "base.inception_4c.5x5_reduce.bias", "base.inception_4c.5x5.weight", "base.inception_4c.5x5.bias", "base.inception_4c.pool_proj.weight", "base.inception_4c.pool_proj.bias", "base.inception_4d.1x1.weight", "base.inception_4d.1x1.bias", "base.inception_4d.3x3_reduce.weight", "base.inception_4d.3x3_reduce.bias", "base.inception_4d.3x3.weight", "base.inception_4d.3x3.bias", "base.inception_4d.5x5_reduce.weight", "base.inception_4d.5x5_reduce.bias", "base.inception_4d.5x5.weight", "base.inception_4d.5x5.bias", "base.inception_4d.pool_proj.weight", "base.inception_4d.pool_proj.bias", "base.inception_4e.1x1.weight", "base.inception_4e.1x1.bias", "base.inception_4e.3x3_reduce.weight", "base.inception_4e.3x3_reduce.bias", "base.inception_4e.3x3.weight", "base.inception_4e.3x3.bias", "base.inception_4e.5x5_reduce.weight", "base.inception_4e.5x5_reduce.bias", "base.inception_4e.5x5.weight", "base.inception_4e.5x5.bias", "base.inception_4e.pool_proj.weight", "base.inception_4e.pool_proj.bias", "base.inception_5a.1x1.weight", "base.inception_5a.1x1.bias", "base.inception_5a.3x3_reduce.weight", "base.inception_5a.3x3_reduce.bias", "base.inception_5a.3x3.weight", "base.inception_5a.3x3.bias", "base.inception_5a.5x5_reduce.weight", "base.inception_5a.5x5_reduce.bias", "base.inception_5a.5x5.weight", "base.inception_5a.5x5.bias", "base.inception_5a.pool_proj.weight", "base.inception_5a.pool_proj.bias", "base.inception_5b.1x1.weight", "base.inception_5b.1x1.bias", "base.inception_5b.3x3_reduce.weight", "base.inception_5b.3x3_reduce.bias", "base.inception_5b.3x3.weight", "base.inception_5b.3x3.bias", "base.inception_5b.5x5_reduce.weight", "base.inception_5b.5x5_reduce.bias", "base.inception_5b.5x5.weight", "base.inception_5b.5x5.bias", "base.inception_5b.pool_proj.weight", "base.inception_5b.pool_proj.bias". 
	Unexpected key(s) in state_dict: "base.bn1.weight", "base.bn1.bias", "base.bn1.running_mean", "base.bn1.running_var", "base.bn1.num_batches_tracked", "base.layer1.0.conv1.weight", "base.layer1.0.bn1.weight", "base.layer1.0.bn1.bias", "base.layer1.0.bn1.running_mean", "base.layer1.0.bn1.running_var", "base.layer1.0.bn1.num_batches_tracked", "base.layer1.0.conv2.weight", "base.layer1.0.bn2.weight", "base.layer1.0.bn2.bias", "base.layer1.0.bn2.running_mean", "base.layer1.0.bn2.running_var", "base.layer1.0.bn2.num_batches_tracked", "base.layer1.1.conv1.weight", "base.layer1.1.bn1.weight", "base.layer1.1.bn1.bias", "base.layer1.1.bn1.running_mean", "base.layer1.1.bn1.running_var", "base.layer1.1.bn1.num_batches_tracked", "base.layer1.1.conv2.weight", "base.layer1.1.bn2.weight", "base.layer1.1.bn2.bias", "base.layer1.1.bn2.running_mean", "base.layer1.1.bn2.running_var", "base.layer1.1.bn2.num_batches_tracked", "base.layer2.0.conv1.weight", "base.layer2.0.bn1.weight", "base.layer2.0.bn1.bias", "base.layer2.0.bn1.running_mean", "base.layer2.0.bn1.running_var", "base.layer2.0.bn1.num_batches_tracked", "base.layer2.0.conv2.weight", "base.layer2.0.bn2.weight", "base.layer2.0.bn2.bias", "base.layer2.0.bn2.running_mean", "base.layer2.0.bn2.running_var", "base.layer2.0.bn2.num_batches_tracked", "base.layer2.0.downsample.0.weight", "base.layer2.0.downsample.1.weight", "base.layer2.0.downsample.1.bias", "base.layer2.0.downsample.1.running_mean", "base.layer2.0.downsample.1.running_var", "base.layer2.0.downsample.1.num_batches_tracked", "base.layer2.1.conv1.weight", "base.layer2.1.bn1.weight", "base.layer2.1.bn1.bias", "base.layer2.1.bn1.running_mean", "base.layer2.1.bn1.running_var", "base.layer2.1.bn1.num_batches_tracked", "base.layer2.1.conv2.weight", "base.layer2.1.bn2.weight", "base.layer2.1.bn2.bias", "base.layer2.1.bn2.running_mean", "base.layer2.1.bn2.running_var", "base.layer2.1.bn2.num_batches_tracked", "base.layer3.0.conv1.weight", "base.layer3.0.bn1.weight", "base.layer3.0.bn1.bias", "base.layer3.0.bn1.running_mean", "base.layer3.0.bn1.running_var", "base.layer3.0.bn1.num_batches_tracked", "base.layer3.0.conv2.weight", "base.layer3.0.bn2.weight", "base.layer3.0.bn2.bias", "base.layer3.0.bn2.running_mean", "base.layer3.0.bn2.running_var", "base.layer3.0.bn2.num_batches_tracked", "base.layer3.0.downsample.0.weight", "base.layer3.0.downsample.1.weight", "base.layer3.0.downsample.1.bias", "base.layer3.0.downsample.1.running_mean", "base.layer3.0.downsample.1.running_var", "base.layer3.0.downsample.1.num_batches_tracked", "base.layer3.1.conv1.weight", "base.layer3.1.bn1.weight", "base.layer3.1.bn1.bias", "base.layer3.1.bn1.running_mean", "base.layer3.1.bn1.running_var", "base.layer3.1.bn1.num_batches_tracked", "base.layer3.1.conv2.weight", "base.layer3.1.bn2.weight", "base.layer3.1.bn2.bias", "base.layer3.1.bn2.running_mean", "base.layer3.1.bn2.running_var", "base.layer3.1.bn2.num_batches_tracked", "base.layer4.0.conv1.weight", "base.layer4.0.bn1.weight", "base.layer4.0.bn1.bias", "base.layer4.0.bn1.running_mean", "base.layer4.0.bn1.running_var", "base.layer4.0.bn1.num_batches_tracked", "base.layer4.0.conv2.weight", "base.layer4.0.bn2.weight", "base.layer4.0.bn2.bias", "base.layer4.0.bn2.running_mean", "base.layer4.0.bn2.running_var", "base.layer4.0.bn2.num_batches_tracked", "base.layer4.0.downsample.0.weight", "base.layer4.0.downsample.1.weight", "base.layer4.0.downsample.1.bias", "base.layer4.0.downsample.1.running_mean", "base.layer4.0.downsample.1.running_var", "base.layer4.0.downsample.1.num_batches_tracked", "base.layer4.1.conv1.weight", "base.layer4.1.bn1.weight", "base.layer4.1.bn1.bias", "base.layer4.1.bn1.running_mean", "base.layer4.1.bn1.running_var", "base.layer4.1.bn1.num_batches_tracked", "base.layer4.1.conv2.weight", "base.layer4.1.bn2.weight", "base.layer4.1.bn2.bias", "base.layer4.1.bn2.running_mean", "base.layer4.1.bn2.running_var", "base.layer4.1.bn2.num_batches_tracked", "base.conv1.weight". 
	size mismatch for linear.weight: copying a param with shape torch.Size([64, 512]) from checkpoint, the shape in current model is torch.Size([64, 1024]).
```

My guess is that the changes in the previous step caused some extra data to be recorded and some went missing. Should there be a modification to this command in order to fix it?

**Comment by lenscloth** [comment]
Since we changed the student model to resnet18, we have to change the backbone model.

Therefore, can you re-launch the following code??
```
python run.py --mode eval --dataset cub200 --base resnet18 --embedding_size 64 --load student/best.pth
```

**Comment by alexzhang0825** [comment]
Thanks for the help. It ran with no problem!

**Comment by zimenglan-sysu-512** [comment]
> @alexzhang0825 In the paper, we utilized resent18 as the backbone network for students in the Table 1.
> `python run_distill.py --dataset cub200 --base googlenet --embedding_size 64 --teacher_base resnet50 --teacher_embedding_size 512 --teacher_load teacher/best.pth --dist_ratio 1 --angle_ratio 2 --save_dir student`
> 
> However, the command above using googlenet as the base student model.
> Moreover, during distiilation not applying l2 normalziation was way better in our experiments.
> 
> It seems that I made wrong quick start script.
> I will modify the README, can you please run this script instead??
> 
> `python run_distill.py --dataset cub200 --base resnet18 --l2normalize false --embedding_size 64 --teacher_base resnet50 --teacher_embedding_size 512 --teacher_load teacher/best.pth --dist_ratio 1 --angle_ratio 2 --save_dir student`

hi @lenscloth  do u mean that, when distillation, the feature from student does not apply l2-norm, but the feature from teacher does?

**Comment by lenscloth** [comment]
@zimenglan-sysu-512 Yes, you are correct

**Comment by zimenglan-sysu-512** [comment]
> @zimenglan-sysu-512 Yes, you are correct

why do this?

**Comment by lenscloth** [comment]
@zimenglan-sysu-512 
We assume that applying l2 normalization prohibit utilizing the entire embedding space.
Because all points must lie on the surface of an unit hypershpere.
To fully utilize the embedding space, we did not apply l2 norm on the student network.

However, for teacher network, we found that applying l2 normalization does helps to find optimal hyper-parameter more easily.
For instance, the margin in the triplet loss.
It is because L2 norm restricts pairwise distance to the range of 0 ~ 2.
However, without L2 norm, the range is unrestricted and very sensitive to the weight initialization.
Therefore, to ease the training process of the teacher we apply l2 norm on the teacher network.

**Comment by zimenglan-sysu-512** [comment]
> @zimenglan-sysu-512
> We assume that applying l2 normalization prohibit utilizing the entire embedding space.
> Because all points must lie on the surface of an unit hypershpere.
> To fully utilize the embedding space, we did not apply l2 norm on the student network.
> 
> However, for teacher network, we found that applying l2 normalization does helps to find optimal hyper-parameter more easily.
> For instance, the margin in the triplet loss.
> It is because L2 norm restricts pairwise distance to the range of 0 ~ 2.
> However, without L2 norm, the range is unrestricted and very sensitive to the weight initialization.
> Therefore, to ease the training process of the teacher we apply l2 norm on the teacher network.

get it, thanks
